# Generated by Django 3.2.2 on 2021-05-10 16:48

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('address', models.CharField(max_length=80)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OD', 'Odrzucone'), ('OC', 'Oczekujące'), ('DR', 'Do realizacji'), ('WT', 'W trakcie realizacji'), ('ZR', 'Zrealizowane')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodId', models.BigAutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('available', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('licensePlate', models.CharField(max_length=9, unique=True)),
                ('carServiceTo', models.DateField()),
                ('type', models.CharField(choices=[('BU', 'Bus'), ('CI', 'Ciężarówka')], max_length=10)),
                ('status', models.CharField(choices=[('SP', 'Sprawny'), ('WW', 'W warsztacie'), ('NI', 'Niesprawny')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Rent4Events.user', verbose_name='ClientUser')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Rent4Events.user', verbose_name='DriverUser')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('birthDate', models.DateField()),
                ('employmentDate', models.DateField(default=datetime.datetime(2021, 5, 10, 16, 48, 9, 63296, tzinfo=utc))),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phoneNumber', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.order', verbose_name='orderId')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.product', verbose_name='productId')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.client', verbose_name='clientId'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('courseDate', models.DateField()),
                ('type', models.CharField(choices=[('DO', 'Dostawa'), ('OD', 'Odbiór')], max_length=7)),
                ('status', models.CharField(choices=[('ZA', 'Zaplanowany'), ('WT', 'W trasie'), ('ZR', 'Zrealizowany')], max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.order', verbose_name='orderId')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.vehicle', verbose_name='vehicleId')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.driver', verbose_name='driverId')),
            ],
        ),
    ]
