# Generated by Django 3.2.2 on 2021-05-11 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employmentDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 11, 0, 21, 8, 389377, tzinfo=utc)),
        ),
    ]
