# Generated by Django 3.2.2 on 2021-05-16 20:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0002_auto_20210511_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catId', models.BigAutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='employmentDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 16, 20, 4, 59, 914321, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.category', verbose_name='catId'),
            preserve_default=False,
        ),
    ]
