# Generated by Django 3.2.2 on 2021-05-16 20:42
from django.conf import settings
from django.db import migrations


def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=1, username="rentAdmin", is_active=True, email="admin@rent4events.com")
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0003_auto_20210516_2205'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
