# Generated by Django 3.2.2 on 2021-05-17 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0005_auto_20210517_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='employmentDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 19, 4, 56, 74307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='Rent4Events.vehicle', verbose_name='vehicleId'),
        ),
    ]
