# Generated by Django 3.2.2 on 2021-05-17 19:11

import datetime

import django
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0006_alter_driver_employmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='employmentDate',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 19, 11, 35, 544196, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('courseDate', models.DateField()),
                ('type', models.CharField(choices=[('DO', 'Dostawa'), ('OD', 'Odbiór')], max_length=7)),
                ('status', models.CharField(choices=[('ZA', 'Zaplanowany'), ('WT', 'W trasie'), ('ZR', 'Zrealizowany')],
                                            max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.order',
                                            verbose_name='orderId')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.vehicle',
                                              verbose_name='vehicleId')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent4Events.driver',
                                             verbose_name='driverId')),
            ],
        ),
    ]
