# Generated by Django 3.2.2 on 2021-05-28 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0010_auto_20210518_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Zaplanowany', 'Zaplanowany'), ('W trasie', 'W trasie'), ('Zrealizowany', 'Zrealizowany')], default='Zaplanowany', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Dostawa', 'Dostawa'), ('Odbiór', 'Odbiór')], max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Odrzucone', 'Odrzucone'), ('Oczekujące', 'Oczekujące'), ('Do realizacji', 'Do realizacji'), ('W trakcie realizacji', 'W trakcie realizacji'), ('Zrealizowane', 'Zrealizowane'), ('Robocze', 'Robocze')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Rent4Events.order', verbose_name='orderId'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('Sprawny', 'Sprawny'), ('W warsztacie', 'W warsztacie'), ('Niesprawny', 'Niesprawny')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Ciężarówka', 'Ciężarówka')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageId', models.BigAutoField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(blank=True, max_length=255, null=True)),
                ('imageUrl', models.CharField(max_length=300)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Rent4Events.product', verbose_name='prodId')),
            ],
        ),
    ]
