# Generated by Django 3.2.2 on 2021-05-28 22:35

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0011_auto_20210528_2355'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('startDate__lt', django.db.models.expressions.F('endDate'))), name='constraint_start_end'),
        ),
        migrations.AddConstraint(
            model_name='orderposition',
            constraint=models.UniqueConstraint(fields=('order_id', 'product_id'), name='constraint_PK_OrderPosition'),
        ),
    ]
