# Generated by Django 3.2.2 on 2021-05-29 02:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0012_auto_20210529_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, error_messages={'check': 'Quantity must be positive!'}),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('totalCost__gte', 0.0)), name='constraint_totalCost_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('available__lte', django.db.models.expressions.F('quantity'))), name='constraint_available_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='constraint_price_greater_than_zero'),
        ),
    ]
