# Generated by Django 3.2.2 on 2021-06-04 20:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0013_auto_20210529_0423'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='constraint_start_end',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('startDate__lte', django.db.models.expressions.F('endDate'))), name='constraint_start_end'),
        ),
    ]
