# Generated by Django 3.2.2 on 2021-06-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0014_auto_20210604_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isTransport',
            field=models.BooleanField(default=False),
        ),
    ]
