# Generated by Django 3.2.2 on 2021-06-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0017_auto_20210612_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Odrzucone', 'Odrzucone'), ('Oczekujące', 'Oczekujące'), ('Do realizacji', 'Do realizacji'), ('W trakcie negocjacji', 'W trakcie negocjacji'), ('W trakcie realizacji', 'W trakcie realizacji'), ('Zrealizowane', 'Zrealizowane'), ('Robocze', 'Robocze'), ('Anulowane', 'Anulowane')], max_length=20),
        ),
    ]
