# Generated by Django 3.2.2 on 2021-06-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
