# Generated by Django 3.2.2 on 2021-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0019_order_isedited'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageField',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
