# Generated by Django 3.2.2 on 2021-06-20 03:39

import Rent4Events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent4Events', '0020_image_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageField',
            field=models.ImageField(blank=True, null=True, upload_to=Rent4Events.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Odrzucone', 'Odrzucone'), ('Oczekujące', 'Oczekujące'), ('Do realizacji', 'Do realizacji'), ('W trakcie negocjacji', 'W trakcie negocjacji'), ('W trakcie realizacji', 'W trakcie realizacji'), ('Zrealizowane', 'Zrealizowane'), ('Robocze', 'Robocze'), ('Anulowane', 'Anulowane'), ('Edytowane', 'Edytowane')], max_length=20),
        ),
    ]
